version: "3.3"
services:
  frontend:
    image: node:14.4-alpine
    depends_on:
      - backend
    working_dir: "/home/node/app"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ..:/home/node/app
    command: "sh -c 'cd frontend; npm run dev-server'"
  backend:
    build: ./backend
    depends_on:
      - mariadb
    working_dir: "/home/node/app"
    expose:
      - "8080"
    volumes:
      - ..:/home/node/app
    command: "sh -c 'cd backend; npm run start:dev'"
    env_file:
      - ../backend/config/dev/env
  backend-https-proxy:
    image: nginx:1.12-alpine
    ports:
      - 8082:8080
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
    depends_on:
      - backend
  #  redis:
  #    image: redis:alpine
  mariadb:
    image: mariadb:10.3.27
    expose:
      - "3306"
    ports:
      - 4306:3306
    volumes:
      - ./mariadb/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "overwatch"
      MYSQL_INITDB_SKIP_TZINFO: "1"
  mariadb-test:
    image: mariadb:10.3.27
    expose:
      - "3306"
    ports:
      - 4307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "overwatch"
      MYSQL_INITDB_SKIP_TZINFO: "1"
  sensu-backend:
    image: sensu/sensu:latest
    volumes:
      - /var/lib/sensu:/var/lib/sensu
    ports:
      - 3000:3000
      - 8080:8080
      - 8081:8081
    environment:
      SENSU_BACKEND_CLUSTER_ADMIN_USERNAME: smol
      SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD: guide
    command: "sensu-backend start --state-dir /var/lib/sensu/sensu-backend --log-level debug"

