version: "3.3"
services:
  frontend:
    image: node:14.4-alpine
    depends_on:
      - backend
    working_dir: "/home/node/app"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ..:/home/node/app
    command: "sh -c 'cd frontend; npm run dev-server'"
  backend:
    image: node:14.4-alpine
    depends_on:
      - mariadb
    working_dir: "/home/node/app"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ..:/home/node/app
    command: "sh -c 'cd backend; npm run start:dev'"
#  redis:
#    image: redis:alpine
  mariadb:
    image: mariadb:10.4
    expose:
      - "3306"
    ports:
      - 4306:3306
    volumes:
      - ./mariadb/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "overwatch"
      MYSQL_INITDB_SKIP_TZINFO: "1"
  mariadb-test:
    image: mariadb:10.4
    expose:
      - "3306"
    ports:
      - 4307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "overwatch"
      MYSQL_INITDB_SKIP_TZINFO: "1"
