version: "3.3"
services:
  redis:
    image: redis:alpine
  mariadb:
    image: mariadb:10.4
    expose:
      - "3306"
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "overwatch"
      MYSQL_INITDB_SKIP_TZINFO: "1"
